require("impatient")
require("lucas.options")
require("lucas.keymaps")
require("lucas.plugins")
require("lucas.mason-config")
require("lucas.colorscheme-config")
require("lucas.lsp-config")
require("lucas.cmp-config")
require("lucas.nvim-tree-config")
require("lucas.comment-config")
require("lucas.telescope-config")
require("lucas.project-config");
require("lucas.bufferline-config")
require("lucas.treesitter-config")
require("lucas.lualine-config")
require("lucas.alpha-config")
require("lucas.autopairs-config")
require("lucas.gitsigns-config")
require("lucas.git-blame-config")
require("lucas.toggleterm-config")
require("lucas.numb-config")
require("lucas.colorizer-config")
require("lucas.which-key-config")
require("lucas.leap-config")
require("lucas.spectre-config")
require("lucas.cybu-config")
require("lucas.tabnine-config")
require("lucas.scrollbar-config")

-- transparency
vim.cmd('hi! Normal ctermbg=NONE guibg=NONE')
vim.cmd('hi! NonText ctermbg=NONE guibg=NONE guifg=NONE ctermfg=NONE')
